name: ci

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Set Go cache paths
        run: |
          echo "GOMODCACHE=$(go env GOMODCACHE)" >> "$GITHUB_ENV"
          echo "GOCACHE=$(go env GOCACHE)" >> "$GITHUB_ENV"

      - name: Cache Go
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.GOMODCACHE }}
            ${{ env.GOCACHE }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test -race ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0

      - name: Build
        run: |
          mkdir -p bin
          go build -o bin/link-shortener ./cmd
